# Generated by Django 4.0.4 on 2022-06-01 07:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('goal', models.IntegerField()),
                ('donated', models.IntegerField(blank=True, default=0, null=True)),
                ('donator_count', models.IntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='uploaded')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donated_amount', models.IntegerField()),
                ('account_number', models.CharField(max_length=20)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
