// Mocks generated by Mockito 5.2.0 from annotations
// in gada_ethiopia_mobile/test/infrastructure/donation/donation_repo_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:gada_ethiopia_mobile/lib.dart' as _i3;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeClient_0 extends _i1.Fake implements _i2.Client {}

class _FakeDonation_1 extends _i1.Fake implements _i3.Donation {}

/// A class which mocks [DonationDataProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockDonationRepository extends _i1.Mock
    implements _i3.DonationDataProvider {
  MockDonationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client => (super.noSuchMethod(Invocation.getter(#client),
      returnValue: _FakeClient_0()) as _i2.Client);
  @override
  _i4.Future<_i3.Donation?> createDonation(_i3.Donation? donation) =>
      (super.noSuchMethod(Invocation.method(#createDonation, [donation]),
              returnValue: Future<_i3.Donation?>.value())
          as _i4.Future<_i3.Donation?>);
  @override
  _i4.Future<void> deleteDonation(int? id) =>
      (super.noSuchMethod(Invocation.method(#deleteDonation, [id]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<List<_i3.Donation>> getDonationsByUser(int? userId) =>
      (super.noSuchMethod(Invocation.method(#getDonationsByUser, [userId]),
              returnValue: Future<List<_i3.Donation>>.value(<_i3.Donation>[]))
          as _i4.Future<List<_i3.Donation>>);
  @override
  _i4.Future<_i3.Donation> updateDonation(int? id, _i3.Donation? donation) =>
      (super.noSuchMethod(Invocation.method(#updateDonation, [id, donation]),
              returnValue: Future<_i3.Donation>.value(_FakeDonation_1()))
          as _i4.Future<_i3.Donation>);
}
